CREATE OR REPLACE VIEW TEACHER_VW AS
SELECT TCHR_ID, USER_ID, USER_RM, USER_FULL_NAME, USER_BIRTH_DATE, USER_CPF, USER_RG, USER_GENRE,
USER_PHOTO, USER_EMAIL_PERS, USER_EMAIL_INST, USER_CEL, USER_TEL FROM TCHR_TBL
INNER JOIN USER_TBL ON TCHR_TBL.USER_FK = USER_TBL.USER_ID;

CREATE OR REPLACE VIEW TEACHER_DOCUMENTS_VW AS
SELECT TCHR_ID, USER_ID, USER_RM, USER_FULL_NAME, USER_BIRTH_DATE, USER_CPF, USER_RG, USER_GENRE,
USER_PHOTO, USER_EMAIL_PERS, USER_EMAIL_INST, USER_CEL, USER_TEL, DOC_ID, DOC_NAME, DOC_DESC, DOC_FILE
FROM TCHR_TBL

CREATE OR REPLACE VIEW STUDENT_VW AS
SELECT STUDENT_ID, USER_ID, USER_RM, USER_FULL_NAME, USER_BIRTH_DATE, USER_CPF, USER_RG, USER_GENRE,
USER_PHOTO, USER_EMAIL_PERS, USER_EMAIL_INST, USER_CEL, USER_TEL 
FROM STUDENT_TB
INNER JOIN USER_TBL ON STUDENT_TBL.USER_FK = USER_TBL.USER_ID;



create OR REPLACE view vw_userDocs (user_name, user_doc, doc_id, user_course) AS
select a.user_full_name, c.doc_name, c.doc_id, e.course_name FROM user_tbl a
INNER JOIN inst_tbl b
ON a.inst_fk = b.inst_id
INNER JOIN doc_tbl c
ON a.user_id = c.user_fk
INNER JOIN inst_course_tbl d
ON b.inst_id = d.inst_fk
INNER JOIN course_tbl e
ON d.course_fk = e.course_id;